[tool.ruff]
line-length = 88
target-version = "py39"

[tool.ruff.lint]
select = ["E", "F", "I"] # Example: Enable pycodestyle errors, pyflakes, and isort rules
ignore = ["E501"] # Example: Ignore line-too-long warnings
